services:
    backend:
        container_name: portfolio-backend-1
        build:
            context: backend
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
        networks:
            - resume_net
        environment:
            - FLASK_ENV=production
            - PORT=5000
            - GOOGLE_APPLICATION_CREDENTIALS=./secrets/credentials.json
        volumes:
            - ./secrets/credentials.json:/secrets/credentials.json:ro

    frontend:
        container_name: portfolio-frontend-1
        build:
            context: .
            dockerfile: frontend/Dockerfile.dev # ✅ Use the development Dockerfile
        ports:
            - "5173:5173"
        depends_on:
            - backend
        networks:
            - resume_net
        volumes:
            - ./frontend:/app
            - /app/node_modules

networks:
    resume_net:
