services:
    backend:
        container_name: portfolio-backend-1 # ✅ Explicitly name the container
        build:
            context: .
            dockerfile: backend/Dockerfile
        ports:
            - "5000:5000" # Exposes backend externally, but Nginx should use the internal network
        networks:
            - resume_net
        environment:
            - FLASK_ENV=production
            - PORT=5000

    frontend:
        container_name: portfolio-frontend-1 # ✅ Explicitly name the container
        build:
            context: .
            dockerfile: frontend/Dockerfile
        ports:
            - "8080:8080"
        depends_on:
            - backend
        networks:
            - resume_net

networks:
    resume_net:
