services:
    nginx:
        image: nginx:latest
        container_name: nginx_server
        ports:
            - "8080:8080"
        volumes:
            - .:/usr/share/nginx/html
            - ./nginx.conf:/etc/nginx/nginx.conf
        restart: unless-stopped
